### PR TITLE
[SET-321] Fix eap-version-bump.sh to match the changes in EAP code base

### PR DESCRIPTION
**Pull request by gaol**
File: 'galleon-pack/src/main/resources/packages/version.txt/content/version.txt' does not exist anymore

### CODE REVIEW

**Review by soul2zimate — APPROVED** [review]

**Comment by baranowb** [comment]
Maybe

if test -f "${PRODUCT_VERSION_ALT_TXT}"; then
   sed ME
fi

?

**Review by xstefank — APPROVED** [review]

**Comment by gaol** [comment]
> Maybe
>
> if test -f "${PRODUCT_VERSION_ALT_TXT}"; then
> sed ME
> fi
>
> ?

@baranowb I don't think we need it anymore, because there is no such file in `7.3`, `7.4` and `7.2`.

**Comment by baranowb** [comment]
Unless we are told to do 7.2 :)

**Review by rpelisse — CHANGES_REQUESTED** [review]
I would not removed the PRODUCT_VERION_ALT_TXT variable has its breaks backward compatibility. I would rather suggest we changes the default values to match the new file layout. Then I would had a test around the "sed" statement to check if the file exists:

if [ -e "{PRODUCT_VERSION_ALT_TXT}" ]; then
   sed...
else
   echo "Please note that there is no such file ${PRODUCT_VERSION_ALT_TXT}"
fi

This way, we don't break backward compatibility.

**Comment by gaol** [comment]
@rpelisse updated to keep backward compatibility, would you please review again? thanks :)

**Review by rpelisse — APPROVED** [review]

**Comment by rpelisse** [comment]
@gaol I'll do one more better and merge this ;)

I've a few more ideas to build on what you did, but for that I'll set up a PR myself.

**Pull request merged**
